spring:
  datasource:
    url: jdbc:mysql://localhost:3307/crud-spring-react?createDatabaseIfNotExist=true&
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
